boom! testing hlist-0.1.0 against stable for nightly
boom! running: cargo +stable build --frozen
boom! creating container for: cargo +stable build --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable build --frozen cargobomb`
blam! c5ce154c1e113c782d2b6f2afc99d35fd71ef0992133345f8d640be3db41f452
boom! running `docker start -a c5ce154c1e113c782d2b6f2afc99d35fd71ef0992133345f8d640be3db41f452`
kablam!    Compiling hlist v0.1.0 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.24 secs
boom! running `docker rm -f c5ce154c1e113c782d2b6f2afc99d35fd71ef0992133345f8d640be3db41f452`
blam! c5ce154c1e113c782d2b6f2afc99d35fd71ef0992133345f8d640be3db41f452
boom! running: cargo +stable test --frozen --no-run
boom! creating container for: cargo +stable test --frozen --no-run
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen --no-run cargobomb`
blam! c2e2136012cb4f6458e919313e058379f85bdb0c61ea7f46bf731c3fa9ceee34
boom! running `docker start -a c2e2136012cb4f6458e919313e058379f85bdb0c61ea7f46bf731c3fa9ceee34`
kablam!    Compiling hlist v0.1.0 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.53 secs
boom! running `docker rm -f c2e2136012cb4f6458e919313e058379f85bdb0c61ea7f46bf731c3fa9ceee34`
blam! c2e2136012cb4f6458e919313e058379f85bdb0c61ea7f46bf731c3fa9ceee34
boom! running: cargo +stable test --frozen
boom! creating container for: cargo +stable test --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen cargobomb`
blam! 24a3bbb409626c527e7e62fa78199360c40aefce02cad62be5b84a711a1e4813
boom! running `docker start -a 24a3bbb409626c527e7e62fa78199360c40aefce02cad62be5b84a711a1e4813`
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
kablam!      Running /target/debug/deps/hlist-93fbd47aafa7db22
blam! 
blam! running 3 tests
blam! test test_get ... ok
blam! test test_get_mut ... ok
blam! test test_index_as_type_parameter ... ok
blam! 
blam! test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured
blam! 
kablam!    Doc-tests hlist
blam! 
blam! running 4 tests
blam! test Find::get_mut_0 ... FAILED
blam! test Find_1 ... FAILED
blam! test Find::get_0 ... FAILED
blam! test Find_0 ... ok
blam! 
blam! failures:
blam! 
blam! ---- Find::get_mut_0 stdout ----
blam! 	error: expected `;`, found `let`
blam!  --> <anon>:5:1
blam!   |
blam! 5 | let mut list = Nil.push(0i32).push(1i64);
blam!   | ^^^
blam! 
blam! error: expected one of `.`, `;`, `?`, or an operator, found `assert`
blam!  --> <anon>:8:1
blam!   |
blam! 8 | assert!(a == 5);
blam!   | ^^^^^^
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'Find::get_mut_0' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:201
blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
blam! 
blam! ---- Find_1 stdout ----
blam! 	error[E0405]: trait `Find` is not in scope
blam!  --> <anon>:2:14
blam!   |
blam! 2 | fn foo<I, L: Find<i32, I>>(list: &L) -> i32 {
blam!   |              ^^^^^^^^^^^^ `Find` is not in scope
blam!   |
blam!   = help: no candidates by the name of `Find` found in your project; maybe you misspelled the name or forgot to import an external crate?
blam! 
blam! error[E0425]: unresolved name `Nil`
blam!  --> <anon>:5:12
blam!   |
blam! 5 | let list = Nil.push("foo").push(5i32).push("bar");
blam!   |            ^^^ unresolved name
blam! 
blam! error: cannot continue compilation due to previous error
blam! 
blam! thread 'Find_1' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:201
blam! thread 'Find_1' panicked at 'couldn't compile the test', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustdoc/test.rs:261
blam! 
blam! ---- Find::get_0 stdout ----
blam! 	error: expected `;`, found `let`
blam!  --> <anon>:5:1
blam!   |
blam! 5 | let list = Nil.push(0i32).push(1i64);
blam!   | ^^^
blam! 
blam! error[E0425]: unresolved name `list`
blam!  --> <anon>:6:15
blam!   |
blam! 6 | let a: i64 = *list.get();
blam!   |               ^^^^ unresolved name
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'Find::get_0' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:201
blam! 
blam! 
blam! failures:
blam!     Find::get_0
blam!     Find::get_mut_0
blam!     Find_1
blam! 
blam! test result: FAILED. 1 passed; 3 failed; 0 ignored; 0 measured
blam! 
kablam! error: test failed
boom! running `docker rm -f 24a3bbb409626c527e7e62fa78199360c40aefce02cad62be5b84a711a1e4813`
blam! 24a3bbb409626c527e7e62fa78199360c40aefce02cad62be5b84a711a1e4813
