boom! testing checked_cast-0.0.3 against stable for nightly
boom! running: cargo +stable build --frozen
boom! creating container for: cargo +stable build --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable build --frozen cargobomb`
blam! 7565e285c32851545fb65c6e2e19e27ac5e7e1e3b20cc074c4a96d230d3fd921
boom! running `docker start -a 7565e285c32851545fb65c6e2e19e27ac5e7e1e3b20cc074c4a96d230d3fd921`
kablam!    Compiling checked_cast v0.0.3 (file:///source)
kablam! warning: unknown lint: `unstable`, #[warn(unknown_lints)] on by default
kablam!  --> src/lib.rs:3:10
kablam!   |
kablam! 3 | #![allow(unstable)]
kablam!   |          ^^^^^^^^
kablam! 
kablam!     Finished dev [unoptimized + debuginfo] target(s) in 0.18 secs
boom! running `docker rm -f 7565e285c32851545fb65c6e2e19e27ac5e7e1e3b20cc074c4a96d230d3fd921`
blam! 7565e285c32851545fb65c6e2e19e27ac5e7e1e3b20cc074c4a96d230d3fd921
boom! running: cargo +stable test --frozen --no-run
boom! creating container for: cargo +stable test --frozen --no-run
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen --no-run cargobomb`
blam! 426f6d3adca1262c37de72aa614af20ff1425e2545621c5da523862ef3ba2540
boom! running `docker start -a 426f6d3adca1262c37de72aa614af20ff1425e2545621c5da523862ef3ba2540`
kablam!    Compiling checked_cast v0.0.3 (file:///source)
kablam! warning: unknown lint: `unstable`, #[warn(unknown_lints)] on by default
kablam!  --> src/lib.rs:3:10
kablam!   |
kablam! 3 | #![allow(unstable)]
kablam!   |          ^^^^^^^^
kablam! 
kablam!     Finished dev [unoptimized + debuginfo] target(s) in 0.38 secs
boom! running `docker rm -f 426f6d3adca1262c37de72aa614af20ff1425e2545621c5da523862ef3ba2540`
blam! 426f6d3adca1262c37de72aa614af20ff1425e2545621c5da523862ef3ba2540
boom! running: cargo +stable test --frozen
boom! creating container for: cargo +stable test --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen cargobomb`
blam! 782646d49e9e90603627b55218f62f1eaa6ddc52e7f5cf2ca30d65850597065d
boom! running `docker start -a 782646d49e9e90603627b55218f62f1eaa6ddc52e7f5cf2ca30d65850597065d`
kablam!     Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
kablam!      Running /target/debug/deps/checked_cast-7074f26665ab07aa
blam! 
blam! running 0 tests
blam! 
blam! test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
blam! 
kablam!    Doc-tests checked_cast
blam! 
blam! running 1 test
blam! test core_0 ... FAILED
blam! 
blam! failures:
blam! 
blam! ---- core_0 stdout ----
blam! 	error[E0433]: failed to resolve. Could not find `Int` in `num`
blam!   --> <anon>:18:40
blam!    |
blam! 18 |     let acast: Option<libc::c_ulong> = checked_cast!(a, libc::c_ulong);
blam!    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `Int` in `num`
blam!    |
blam!    = note: this error originates in a macro outside of the current crate
blam! 
blam! error[E0433]: failed to resolve. Could not find `Int` in `num`
blam!   --> <anon>:18:40
blam!    |
blam! 18 |     let acast: Option<libc::c_ulong> = checked_cast!(a, libc::c_ulong);
blam!    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `Int` in `num`
blam!    |
blam!    = note: this error originates in a macro outside of the current crate
blam! 
blam! error[E0433]: failed to resolve. Could not find `Int` in `num`
blam!   --> <anon>:27:38
blam!    |
blam! 27 |     let bcast: Option<libc::c_int> = checked_cast!(b, libc::c_int);
blam!    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `Int` in `num`
blam!    |
blam!    = note: this error originates in a macro outside of the current crate
blam! 
blam! error[E0433]: failed to resolve. Could not find `Int` in `num`
blam!   --> <anon>:27:38
blam!    |
blam! 27 |     let bcast: Option<libc::c_int> = checked_cast!(b, libc::c_int);
blam!    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `Int` in `num`
blam!    |
blam!    = note: this error originates in a macro outside of the current crate
blam! 
blam! error[E0433]: failed to resolve. Could not find `Int` in `num`
blam!   --> <anon>:35:39
blam!    |
blam! 35 |     let ccast: Option<libc::c_uint> = checked_cast!(c, libc::c_uint);
blam!    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `Int` in `num`
blam!    |
blam!    = note: this error originates in a macro outside of the current crate
blam! 
blam! error[E0433]: failed to resolve. Could not find `Int` in `num`
blam!   --> <anon>:35:39
blam!    |
blam! 35 |     let ccast: Option<libc::c_uint> = checked_cast!(c, libc::c_uint);
blam!    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `Int` in `num`
blam!    |
blam!    = note: this error originates in a macro outside of the current crate
blam! 
blam! error[E0412]: cannot find type `int` in this scope
blam!   --> <anon>:42:12
blam!    |
blam! 42 |     let d: int = 2314;
blam!    |            ^^^ not found in this scope
blam! 
blam! error[E0433]: failed to resolve. Could not find `Int` in `num`
blam!   --> <anon>:43:29
blam!    |
blam! 43 |     let dcast: Option<u8> = checked_cast!(d, u8);
blam!    |                             ^^^^^^^^^^^^^^^^^^^^ Could not find `Int` in `num`
blam!    |
blam!    = note: this error originates in a macro outside of the current crate
blam! 
blam! error[E0433]: failed to resolve. Could not find `Int` in `num`
blam!   --> <anon>:43:29
blam!    |
blam! 43 |     let dcast: Option<u8> = checked_cast!(d, u8);
blam!    |                             ^^^^^^^^^^^^^^^^^^^^ Could not find `Int` in `num`
blam!    |
blam!    = note: this error originates in a macro outside of the current crate
blam! 
blam! error[E0433]: failed to resolve. Could not find `Int` in `num`
blam!   --> <anon>:53:22
blam!    |
blam! 53 |     let ecast: i16 = checked_cast!(e, i16).unwrap();
blam!    |                      ^^^^^^^^^^^^^^^^^^^^^ Could not find `Int` in `num`
blam!    |
blam!    = note: this error originates in a macro outside of the current crate
blam! 
blam! error[E0433]: failed to resolve. Could not find `Int` in `num`
blam!   --> <anon>:53:22
blam!    |
blam! 53 |     let ecast: i16 = checked_cast!(e, i16).unwrap();
blam!    |                      ^^^^^^^^^^^^^^^^^^^^^ Could not find `Int` in `num`
blam!    |
blam!    = note: this error originates in a macro outside of the current crate
blam! 
blam! error: The attribute `should_fail` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
blam!   --> <anon>:49:1
blam!    |
blam! 49 | #[should_fail]
blam!    | ^^^^^^^^^^^^^^
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
blam! 
blam! 
blam! failures:
blam!     core_0
blam! 
blam! test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
blam! 
kablam! error: test failed
boom! running `docker rm -f 782646d49e9e90603627b55218f62f1eaa6ddc52e7f5cf2ca30d65850597065d`
blam! 782646d49e9e90603627b55218f62f1eaa6ddc52e7f5cf2ca30d65850597065d
