boom! testing xcb-0.7.6 against stable for nightly
boom! running: cargo +stable build --frozen
boom! creating container for: cargo +stable build --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable build --frozen cargobomb`
blam! beca9a7f794dea724d5058f2f0d0586abad4d96662871f39125f7e339785cd67
boom! running `docker start -a beca9a7f794dea724d5058f2f0d0586abad4d96662871f39125f7e339785cd67`
kablam!    Compiling xcb v0.7.6 (file:///source)
kablam! error: failed to run custom build command for `xcb v0.7.6 (file:///source)`
kablam! process didn't exit successfully: `/target/debug/build/xcb-604f50069650549d/build-script-build` (exit code: 101)
kablam! --- stderr
kablam! error occured in handler:  ('request: ', ('xcb', 'DRI3', 'FDFromFence'))
kablam! Traceback (most recent call last):
kablam!   File "/source/rs_client.py", line 2401, in <module>
kablam!     module.generate()
kablam!   File "/source/xcbgen/state.py", line 108, in generate
kablam!     self.close()
kablam!   File "/source/rs_client.py", line 291, in rs_close
kablam!     _f.writeout(os.path.join(module.rs_srcdir, "ffi", "%s.rs" % _module_name(_ns.ext_name)))
kablam!   File "/source/rs_client.py", line 115, in writeout
kablam!     with open(path, 'w') as f:
kablam! OSError: [Errno 30] Read-only file system: '/source/src/ffi/dri3.rs'
kablam! thread 'main' panicked at 'processing of /source/xml/dri3.xml returned non-zero (1)', build.rs:73
kablam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
kablam! 
boom! running `docker rm -f beca9a7f794dea724d5058f2f0d0586abad4d96662871f39125f7e339785cd67`
blam! beca9a7f794dea724d5058f2f0d0586abad4d96662871f39125f7e339785cd67
