boom! testing jfs-0.2.2 against stable for nightly
boom! running: cargo +stable build --frozen
boom! creating container for: cargo +stable build --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable build --frozen cargobomb`
blam! dc63ebdbe88d1a0c4d3776f432eb5c384491a7b76fcc8928fedae2c58cd56725
boom! running `docker start -a dc63ebdbe88d1a0c4d3776f432eb5c384491a7b76fcc8928fedae2c58cd56725`
kablam!    Compiling jfs v0.2.2 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 1.38 secs
boom! running `docker rm -f dc63ebdbe88d1a0c4d3776f432eb5c384491a7b76fcc8928fedae2c58cd56725`
blam! dc63ebdbe88d1a0c4d3776f432eb5c384491a7b76fcc8928fedae2c58cd56725
boom! running: cargo +stable test --frozen --no-run
boom! creating container for: cargo +stable test --frozen --no-run
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen --no-run cargobomb`
blam! 40809d28e1ba3966f1a5a9f527c66d5e38539c0750503d4d246e2697fb8b5666
boom! running `docker start -a 40809d28e1ba3966f1a5a9f527c66d5e38539c0750503d4d246e2697fb8b5666`
kablam!    Compiling jfs v0.2.2 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 4.75 secs
boom! running `docker rm -f 40809d28e1ba3966f1a5a9f527c66d5e38539c0750503d4d246e2697fb8b5666`
blam! 40809d28e1ba3966f1a5a9f527c66d5e38539c0750503d4d246e2697fb8b5666
boom! running: cargo +stable test --frozen
boom! creating container for: cargo +stable test --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen cargobomb`
blam! 7ad2a8e968edd767d15ac89aca702f2adfdd76f6b786404b5d0a9904c870d221
boom! running `docker start -a 7ad2a8e968edd767d15ac89aca702f2adfdd76f6b786404b5d0a9904c870d221`
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
kablam!      Running /target/debug/deps/jfs-2ee96bfb1f30942d
blam! 
blam! running 0 tests
blam! 
blam! test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
blam! 
kablam!      Running /target/debug/lib-6577f94bdfe51f14
blam! 
blam! running 20 tests
blam! test delete ... FAILED
blam! test delete_non_existent ... FAILED
blam! test get ... FAILED
blam! test get_all ... FAILED
blam! test pretty_print_file_content ... FAILED
blam! test get_non_existent ... FAILED
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
kablam! thread 'thread 'thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
kablam! <unnamed><unnamed>' panicked at '' panicked at 'assertion failed: Store::new(&d).is_ok()assertion failed: Store::new(&d).is_ok()', ', tests/lib.rstests/lib.rs::104104
kablam! 
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
blam! test save_and_read_multi_threaded ... FAILED
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
blam! test save ... FAILED
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
blam! test save_empty_obj ... FAILED
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
blam! test new_multi_threaded ... FAILED
blam! test save_with_id ... FAILED
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
blam! test single_delete_non_existent ... FAILED
blam! test single_delete ... FAILED
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new(&d).is_ok()', tests/lib.rs:104
blam! test single_get_all ... FAILED
blam! test single_get ... FAILED
blam! test single_new_multi_threaded ... ok
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
blam! test single_get_non_existent ... FAILED
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
kablam! thread '<unnamed>' panicked at 'assertion failed: Store::new_with_cfg(&n, cfg).is_ok()', tests/lib.rs:312
blam! test single_save ... FAILED
blam! test single_save_without_file_name_ext ... FAILED
kablam! error: test failed
blam! test single_save_and_read_multi_threaded ... FAILED
blam! 
blam! failures:
blam! 
blam! ---- delete stdout ----
blam! 	thread 'delete' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 30, message: "Read-only file system" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- delete_non_existent stdout ----
blam! 	thread 'delete_non_existent' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 30, message: "Read-only file system" } }', ../src/libcore/result.rs:837
blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
blam! 
blam! ---- get stdout ----
blam! 	thread 'get' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 30, message: "Read-only file system" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- get_all stdout ----
blam! 	thread 'get_all' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 30, message: "Read-only file system" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- pretty_print_file_content stdout ----
blam! 	thread 'pretty_print_file_content' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 30, message: "Read-only file system" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- get_non_existent stdout ----
blam! 	thread 'get_non_existent' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 30, message: "Read-only file system" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- save_and_read_multi_threaded stdout ----
blam! 	thread 'save_and_read_multi_threaded' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 30, message: "Read-only file system" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- save stdout ----
blam! 	thread 'save' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 30, message: "Read-only file system" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- save_empty_obj stdout ----
blam! 	thread 'save_empty_obj' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 30, message: "Read-only file system" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- new_multi_threaded stdout ----
blam! 	thread 'new_multi_threaded' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:837
blam! 
blam! ---- save_with_id stdout ----
blam! 	thread 'save_with_id' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 30, message: "Read-only file system" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- single_delete_non_existent stdout ----
blam! 	thread 'single_delete_non_existent' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- single_delete stdout ----
blam! 	thread 'single_delete' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- single_get_all stdout ----
blam! 	thread 'single_get_all' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- single_get stdout ----
blam! 	thread 'single_get' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- single_get_non_existent stdout ----
blam! 	thread 'single_get_non_existent' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- single_save stdout ----
blam! 	thread 'single_save' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- single_save_without_file_name_ext stdout ----
blam! 	thread 'single_save_without_file_name_ext' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- single_save_and_read_multi_threaded stdout ----
blam! 	thread 'single_save_and_read_multi_threaded' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
blam! 
blam! 
blam! failures:
blam!     delete
blam!     delete_non_existent
blam!     get
blam!     get_all
blam!     get_non_existent
blam!     new_multi_threaded
blam!     pretty_print_file_content
blam!     save
blam!     save_and_read_multi_threaded
blam!     save_empty_obj
blam!     save_with_id
blam!     single_delete
blam!     single_delete_non_existent
blam!     single_get
blam!     single_get_all
blam!     single_get_non_existent
blam!     single_save
blam!     single_save_and_read_multi_threaded
blam!     single_save_without_file_name_ext
blam! 
blam! test result: FAILED. 1 passed; 19 failed; 0 ignored; 0 measured
blam! 
boom! running `docker rm -f 7ad2a8e968edd767d15ac89aca702f2adfdd76f6b786404b5d0a9904c870d221`
blam! 7ad2a8e968edd767d15ac89aca702f2adfdd76f6b786404b5d0a9904c870d221
