boom! testing sharedlib-7.0.0 against stable for beta
boom! running: cargo +stable build --frozen
boom! creating container for: cargo +stable build --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/beta/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/beta/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable build --frozen cargobomb`
blam! 8b7e8456c12bd7581381b097c37d220d74c8bbbb804e6b4b9ae0db4678ef1f36
boom! running `docker start -a 8b7e8456c12bd7581381b097c37d220d74c8bbbb804e6b4b9ae0db4678ef1f36`
kablam!    Compiling sharedlib v7.0.0 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 1.86 secs
boom! running `docker rm -f 8b7e8456c12bd7581381b097c37d220d74c8bbbb804e6b4b9ae0db4678ef1f36`
blam! 8b7e8456c12bd7581381b097c37d220d74c8bbbb804e6b4b9ae0db4678ef1f36
boom! running: cargo +stable test --frozen --no-run
boom! creating container for: cargo +stable test --frozen --no-run
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/beta/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/beta/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen --no-run cargobomb`
blam! 7f800c9e7b7f3435ea933ef2f3a4187bbed5238776164354334fd33f331e9c1d
boom! running `docker start -a 7f800c9e7b7f3435ea933ef2f3a4187bbed5238776164354334fd33f331e9c1d`
kablam!    Compiling sharedlib v7.0.0 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 1.43 secs
boom! running `docker rm -f 7f800c9e7b7f3435ea933ef2f3a4187bbed5238776164354334fd33f331e9c1d`
blam! 7f800c9e7b7f3435ea933ef2f3a4187bbed5238776164354334fd33f331e9c1d
boom! running: cargo +stable test --frozen
boom! creating container for: cargo +stable test --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/beta/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/beta/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen cargobomb`
blam! d5b83a36b9869219f4576526645a2b683d960726669c7354dda69fff21bf102f
boom! running `docker start -a d5b83a36b9869219f4576526645a2b683d960726669c7354dda69fff21bf102f`
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
kablam!      Running /target/debug/deps/sharedlib-2623274f826a4d39
blam! 
blam! running 10 tests
blam! test test::shared::create_struct_arc ... FAILED
blam! test test::shared::add_2_numbers ... FAILED
blam! test test::shared::check_test_value ... FAILED
blam! test test::shared::load_examplelib ... FAILED
blam! test test::shared::create_struct_safe ... FAILED
blam! test test::shared::create_struct_unsafe ... FAILED
blam! test test::unix::shared::libm_ceil ... FAILED
blam! test test::unix::shared::libm_ceil0 ... FAILED
blam! test test::unix::shared::new_m ... ok
blam! test test::unix::shared::new_libm ... FAILED
blam! 
blam! failures:
blam! 
blam! ---- test::shared::create_struct_arc stdout ----
blam! 	thread 'test::shared::create_struct_arc' panicked at 'called `Result::unwrap()` on an `Err` value: Error(LibraryOpen("test/.build/libexamplelib.so"), State { next_error: Some(Error(OsError("test/.build/libexamplelib.soadd_u32s\u{2}: cannot open shared object file: No such file or directory", "dlopen"), State { next_error: None })) })', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
blam! 
blam! ---- test::shared::add_2_numbers stdout ----
blam! 	thread 'test::shared::add_2_numbers' panicked at 'called `Result::unwrap()` on an `Err` value: Error(LibraryOpen("test/.build/libexamplelib.so"), State { next_error: Some(Error(OsError("test/.build/libexamplelib.soadd_u32s\u{2}: cannot open shared object file: No such file or directory", "dlopen"), State { next_error: None })) })', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! 
blam! ---- test::shared::check_test_value stdout ----
blam! 	thread 'test::shared::check_test_value' panicked at 'called `Result::unwrap()` on an `Err` value: Error(LibraryOpen("test/.build/libexamplelib.so"), State { next_error: Some(Error(OsError("test/.build/libexamplelib.soadd_u32s\u{2}: cannot open shared object file: No such file or directory", "dlopen"), State { next_error: None })) })', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! 
blam! ---- test::shared::load_examplelib stdout ----
blam! 	thread 'test::shared::load_examplelib' panicked at 'called `Result::unwrap()` on an `Err` value: Error(LibraryOpen("test/.build/libexamplelib.so"), State { next_error: Some(Error(OsError("test/.build/libexamplelib.soadd_u32s\u{2}: cannot open shared object file: No such file or directory", "dlopen"), State { next_error: None })) })', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! 
blam! ---- test::shared::create_struct_safe stdout ----
blam! 	thread 'test::shared::create_struct_safe' panicked at 'called `Result::unwrap()` on an `Err` value: Error(LibraryOpen("test/.build/libexamplelib.so"), State { next_error: Some(Error(OsError("test/.build/libexamplelib.soadd_u32s\u{2}: cannot open shared object file: No such file or directory", "dlopen"), State { next_error: None })) })', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! 
blam! ---- test::shared::create_struct_unsafe stdout ----
blam! 	thread 'test::shared::create_struct_unsafe' panicked at 'called `Result::unwrap()` on an `Err` value: Error(LibraryOpen("test/.build/libexamplelib.so"), State { next_error: Some(Error(OsError("test/.build/libexamplelib.soadd_u32s\u{2}: cannot open shared object file: No such file or directory", "dlopen"), State { next_error: None })) })', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! 
blam! ---- test::unix::shared::libm_ceil stdout ----
blam! 	thread 'test::unix::shared::libm_ceil' panicked at 'called `Result::unwrap()` on an `Err` value: Error(LibraryOpen("libm.so.6"), State { next_error: Some(Error(OsError("libm.so.6mceilceil: cannot open shared object file: No such file or directory", "dlopen"), State { next_error: None })) })', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! 
blam! ---- test::unix::shared::libm_ceil0 stdout ----
blam! 	thread 'test::unix::shared::libm_ceil0' panicked at 'called `Result::unwrap()` on an `Err` value: Error(LibraryOpen("libm.so.6"), State { next_error: Some(Error(OsError("libm.so.6mceilceil: cannot open shared object file: No such file or directory", "dlopen"), State { next_error: None })) })', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! 
blam! ---- test::unix::shared::new_libm stdout ----
blam! 	thread 'test::unix::shared::new_libm' panicked at 'called `Result::unwrap()` on an `Err` value: Error(LibraryOpen("libm.so.6"), State { next_error: Some(Error(OsError("libm.so.6mceilceil: cannot open shared object file: No such file or directory", "dlopen"), State { next_error: None })) })', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! 
blam! 
blam! failures:
blam!     test::shared::add_2_numbers
blam!     test::shared::check_test_value
blam!     test::shared::create_struct_arc
blam!     test::shared::create_struct_safe
blam!     test::shared::create_struct_unsafe
blam!     test::shared::load_examplelib
blam!     test::unix::shared::libm_ceil
blam!     test::unix::shared::libm_ceil0
blam!     test::unix::shared::new_libm
blam! 
blam! test result: FAILED. 1 passed; 9 failed; 0 ignored; 0 measured
blam! 
kablam! error: test failed
boom! running `docker rm -f d5b83a36b9869219f4576526645a2b683d960726669c7354dda69fff21bf102f`
blam! d5b83a36b9869219f4576526645a2b683d960726669c7354dda69fff21bf102f
