boom! testing metaheuristics-0.0.6 against stable for nightly
boom! running: cargo +stable build --frozen
boom! creating container for: cargo +stable build --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable build --frozen cargobomb`
blam! 3ce732e009ed237067b2efff6ad6c80587ef6187241bf56b2e786cabee58b216
boom! running `docker start -a 3ce732e009ed237067b2efff6ad6c80587ef6187241bf56b2e786cabee58b216`
kablam!    Compiling metaheuristics v0.0.6 (file:///source)
kablam!     Finished dev [unoptimized + debuginfo] target(s) in 0.49 secs
boom! running `docker rm -f 3ce732e009ed237067b2efff6ad6c80587ef6187241bf56b2e786cabee58b216`
blam! 3ce732e009ed237067b2efff6ad6c80587ef6187241bf56b2e786cabee58b216
boom! running: cargo +stable test --frozen --no-run
boom! creating container for: cargo +stable test --frozen --no-run
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen --no-run cargobomb`
blam! ea43aa552dad4e68553f87077c3cf272b6ceac479c588c116ea4fd432277423a
boom! running `docker start -a ea43aa552dad4e68553f87077c3cf272b6ceac479c588c116ea4fd432277423a`
kablam!    Compiling metaheuristics v0.0.6 (file:///source)
kablam!     Finished dev [unoptimized + debuginfo] target(s) in 1.45 secs
boom! running `docker rm -f ea43aa552dad4e68553f87077c3cf272b6ceac479c588c116ea4fd432277423a`
blam! ea43aa552dad4e68553f87077c3cf272b6ceac479c588c116ea4fd432277423a
boom! running: cargo +stable test --frozen
boom! creating container for: cargo +stable test --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen cargobomb`
blam! cdcc8048bc7ea2493f66c89b446bbf6afa4b9c2f1f3a4d714788fd134d17ad42
boom! running `docker start -a cdcc8048bc7ea2493f66c89b446bbf6afa4b9c2f1f3a4d714788fd134d17ad42`
kablam!     Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
kablam!      Running /target/debug/deps/metaheuristics-b0c6eca544f363dc
blam! 
blam! running 0 tests
blam! 
blam! test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
blam! 
kablam!    Doc-tests metaheuristics
blam! 
blam! running 14 tests
blam! test Metaheuristics::generate_candidate_0 ... FAILED
blam! test Metaheuristics::tweak_candidate_0 ... FAILED
blam! test Metaheuristics::clone_candidate_0 ... FAILED
blam! test Metaheuristics::rank_candidate_0 ... FAILED
blam! test _0 ... FAILED
blam! test hill_climbing::random_restarts::solve_0 ... FAILED
blam! test hill_climbing::random_restarts_0 ... FAILED
blam! test hill_climbing::solve_0 ... FAILED
blam! test hill_climbing_0 ... FAILED
blam! test random_search::solve_0 ... FAILED
blam! test random_search_0 ... FAILED
blam! test simulated_annealing_0 ... FAILED
blam! test simulated_annealing::solve_0 ... FAILED
blam! test simulated_annealing_1 ... FAILED
blam! 
blam! failures:
blam! 
blam! ---- Metaheuristics::generate_candidate_0 stdout ----
blam! 	error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:2:18
blam!   |
blam! 2 |  let candidate = problem.generate_candidate();
blam!   |                  ^^^^^^^ not found in this scope
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
blam! 
blam! ---- Metaheuristics::tweak_candidate_0 stdout ----
blam! 	error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:2:22
blam!   |
blam! 2 |  let new_candidate = problem.tweak_candidate(&old_candidate);
blam!   |                      ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `old_candidate` in this scope
blam!  --> <anon>:2:47
blam!   |
blam! 2 |  let new_candidate = problem.tweak_candidate(&old_candidate);
blam!   |                                               ^^^^^^^^^^^^^ not found in this scope
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! 
blam! ---- Metaheuristics::clone_candidate_0 stdout ----
blam! 	error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:2:22
blam!   |
blam! 2 |  let new_candidate = problem.clone_candidate(&old_candidate);
blam!   |                      ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `old_candidate` in this scope
blam!  --> <anon>:2:47
blam!   |
blam! 2 |  let new_candidate = problem.clone_candidate(&old_candidate);
blam!   |                                               ^^^^^^^^^^^^^ not found in this scope
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! 
blam! ---- Metaheuristics::rank_candidate_0 stdout ----
blam! 	error: inclusive range with no end
blam!  --> <anon>:4:2
blam!   |
blam! 4 |  }
blam!   |  ^
blam!   |
blam!   = help: inclusive ranges must be bounded at the end (`...b` or `a...b`)
blam! 
blam! error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:2:5
blam!   |
blam! 2 |  if problem.rank_candidate(&new_candidate) > problem.rank_candidate(&old_candidate) {
blam!   |     ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `new_candidate` in this scope
blam!  --> <anon>:2:29
blam!   |
blam! 2 |  if problem.rank_candidate(&new_candidate) > problem.rank_candidate(&old_candidate) {
blam!   |                             ^^^^^^^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:2:46
blam!   |
blam! 2 |  if problem.rank_candidate(&new_candidate) > problem.rank_candidate(&old_candidate) {
blam!   |                                              ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `old_candidate` in this scope
blam!  --> <anon>:2:70
blam!   |
blam! 2 |  if problem.rank_candidate(&new_candidate) > problem.rank_candidate(&old_candidate) {
blam!   |                                                                      ^^^^^^^^^^^^^ not found in this scope
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! 
blam! ---- _0 stdout ----
blam! 	error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:3:59
blam!   |
blam! 3 |  let solution = metaheuristics::hill_climbing::solve(&mut problem, runtime);
blam!   |                                                           ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `runtime` in this scope
blam!  --> <anon>:3:68
blam!   |
blam! 3 |  let solution = metaheuristics::hill_climbing::solve(&mut problem, runtime);
blam!   |                                                                    ^^^^^^^ not found in this scope
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! 
blam! ---- hill_climbing::random_restarts::solve_0 stdout ----
blam! 	error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:4:10
blam!   |
blam! 4 |     &mut problem,
blam!   |          ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `runtime` in this scope
blam!  --> <anon>:5:5
blam!   |
blam! 5 |     runtime,
blam!   |     ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `probability` in this scope
blam!  --> <anon>:6:5
blam!   |
blam! 6 |     probability
blam!   |     ^^^^^^^^^^^ not found in this scope
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! 
blam! ---- hill_climbing::random_restarts_0 stdout ----
blam! 	error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:4:10
blam!   |
blam! 4 |     &mut problem,
blam!   |          ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `runtime` in this scope
blam!  --> <anon>:5:5
blam!   |
blam! 5 |     runtime,
kablam! error: test failed
blam!   |     ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `probability` in this scope
blam!  --> <anon>:6:5
blam!   |
blam! 6 |     probability
blam!   |     ^^^^^^^^^^^ not found in this scope
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! 
blam! ---- hill_climbing::solve_0 stdout ----
blam! 	error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:3:58
blam!   |
blam! 3 | let solution = metaheuristics::hill_climbing::solve(&mut problem, runtime);
blam!   |                                                          ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `runtime` in this scope
blam!  --> <anon>:3:67
blam!   |
blam! 3 | let solution = metaheuristics::hill_climbing::solve(&mut problem, runtime);
blam!   |                                                                   ^^^^^^^ not found in this scope
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! 
blam! ---- hill_climbing_0 stdout ----
blam! 	error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:3:58
blam!   |
blam! 3 | let solution = metaheuristics::hill_climbing::solve(&mut problem, runtime);
blam!   |                                                          ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `runtime` in this scope
blam!  --> <anon>:3:67
blam!   |
blam! 3 | let solution = metaheuristics::hill_climbing::solve(&mut problem, runtime);
blam!   |                                                                   ^^^^^^^ not found in this scope
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! 
blam! ---- random_search::solve_0 stdout ----
blam! 	error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:3:58
blam!   |
blam! 3 | let solution = metaheuristics::random_search::solve(&mut problem, runtime);
blam!   |                                                          ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `runtime` in this scope
blam!  --> <anon>:3:67
blam!   |
blam! 3 | let solution = metaheuristics::random_search::solve(&mut problem, runtime);
blam!   |                                                                   ^^^^^^^ not found in this scope
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! 
blam! ---- random_search_0 stdout ----
blam! 	error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:3:58
blam!   |
blam! 3 | let solution = metaheuristics::random_search::solve(&mut problem, runtime);
blam!   |                                                          ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `runtime` in this scope
blam!  --> <anon>:3:67
blam!   |
blam! 3 | let solution = metaheuristics::random_search::solve(&mut problem, runtime);
blam!   |                                                                   ^^^^^^^ not found in this scope
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! 
blam! ---- simulated_annealing_0 stdout ----
blam! 	error[E0425]: cannot find function `P` in this scope
blam!  --> <anon>:2:1
blam!   |
blam! 2 | P(t) = e^(-10*(t^3))
blam!   | ^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `t` in this scope
blam!  --> <anon>:2:3
blam!   |
blam! 2 | P(t) = e^(-10*(t^3))
blam!   |   ^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `e` in this scope
blam!  --> <anon>:2:8
blam!   |
blam! 2 | P(t) = e^(-10*(t^3))
blam!   |        ^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `t` in this scope
blam!  --> <anon>:2:16
blam!   |
blam! 2 | P(t) = e^(-10*(t^3))
blam!   |                ^ not found in this scope
blam! 
blam! error[E0070]: invalid left-hand side expression
blam!  --> <anon>:2:1
blam!   |
blam! 2 | P(t) = e^(-10*(t^3))
blam!   | ^^^^^^^^^^^^^^^^^^^^ left-hand of expression not valid
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! 
blam! ---- simulated_annealing::solve_0 stdout ----
blam! 	error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:3:64
blam!   |
blam! 3 | let solution = metaheuristics::simulated_annealing::solve(&mut problem, runtime);
blam!   |                                                                ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `runtime` in this scope
blam!  --> <anon>:3:73
blam!   |
blam! 3 | let solution = metaheuristics::simulated_annealing::solve(&mut problem, runtime);
blam!   |                                                                         ^^^^^^^ not found in this scope
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! 
blam! ---- simulated_annealing_1 stdout ----
blam! 	error[E0425]: cannot find value `problem` in this scope
blam!  --> <anon>:3:64
blam!   |
blam! 3 | let solution = metaheuristics::simulated_annealing::solve(&mut problem, runtime);
blam!   |                                                                ^^^^^^^ not found in this scope
blam! 
blam! error[E0425]: cannot find value `runtime` in this scope
blam!  --> <anon>:3:73
blam!   |
blam! 3 | let solution = metaheuristics::simulated_annealing::solve(&mut problem, runtime);
blam!   |                                                                         ^^^^^^^ not found in this scope
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/librustc/session/mod.rs:203
blam! 
blam! 
blam! failures:
blam!     Metaheuristics::clone_candidate_0
blam!     Metaheuristics::generate_candidate_0
blam!     Metaheuristics::rank_candidate_0
blam!     Metaheuristics::tweak_candidate_0
blam!     _0
blam!     hill_climbing::random_restarts::solve_0
blam!     hill_climbing::random_restarts_0
blam!     hill_climbing::solve_0
blam!     hill_climbing_0
blam!     random_search::solve_0
blam!     random_search_0
blam!     simulated_annealing::solve_0
blam!     simulated_annealing_0
blam!     simulated_annealing_1
blam! 
blam! test result: FAILED. 0 passed; 14 failed; 0 ignored; 0 measured
blam! 
boom! running `docker rm -f cdcc8048bc7ea2493f66c89b446bbf6afa4b9c2f1f3a4d714788fd134d17ad42`
blam! cdcc8048bc7ea2493f66c89b446bbf6afa4b9c2f1f3a4d714788fd134d17ad42
