boom! testing deckofcards-0.3.4 against stable for nightly
boom! running: cargo +stable build --frozen
boom! creating container for: cargo +stable build --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable build --frozen cargobomb`
blam! 9fd0b0740c2a361801880f42330e9b2791af855b49ac1b7671135b93edd64e14
boom! running `docker start -a 9fd0b0740c2a361801880f42330e9b2791af855b49ac1b7671135b93edd64e14`
kablam!    Compiling deckofcards v0.3.4 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 1.2 secs
boom! running `docker rm -f 9fd0b0740c2a361801880f42330e9b2791af855b49ac1b7671135b93edd64e14`
blam! 9fd0b0740c2a361801880f42330e9b2791af855b49ac1b7671135b93edd64e14
boom! running: cargo +stable test --frozen --no-run
boom! creating container for: cargo +stable test --frozen --no-run
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen --no-run cargobomb`
blam! d00567a15540664240d8500033c5bf1fa4ef5fa5f715912f51dde657cb1ea00f
boom! running `docker start -a d00567a15540664240d8500033c5bf1fa4ef5fa5f715912f51dde657cb1ea00f`
kablam!    Compiling deckofcards v0.3.4 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 3.26 secs
boom! running `docker rm -f d00567a15540664240d8500033c5bf1fa4ef5fa5f715912f51dde657cb1ea00f`
blam! d00567a15540664240d8500033c5bf1fa4ef5fa5f715912f51dde657cb1ea00f
boom! running: cargo +stable test --frozen
boom! creating container for: cargo +stable test --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen cargobomb`
blam! bf28da86a316e75fd99550307f3adb51f4343fb151ccee47f840524990802552
boom! running `docker start -a bf28da86a316e75fd99550307f3adb51f4343fb151ccee47f840524990802552`
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
kablam!      Running /target/debug/deps/deckofcards-a564f589fb582c87
blam! 
blam! running 25 tests
blam! test tests::card_all_cards ... ok
blam! test tests::card_equality ... ok
blam! test tests::card_from_str ... ok
blam! test tests::deck_clone ... ok
blam! test tests::card_to_str ... ok
blam! test tests::deck_dealt_cards ... ok
blam! test tests::deck_count ... ok
blam! test tests::deck_reset ... ok
blam! test tests::deck_shuffle_same_cards ... ok
blam! test tests::deck_unique ... ok
blam! test tests::deck_shuffle_new_order ... ok
blam! test tests::hand_combine_hands ... ok
blam! test tests::hand_cards_of_suit ... ok
blam! test tests::hand_cards_of_rank ... ok
blam! test tests::rank_char ... ok
blam! test tests::hand_sort ... ok
blam! test tests::rank_sort ... ok
blam! test tests::rank_cmp ... ok
blam! test tests::hand_sort_shuffle_deck ... ok
blam! test tests::suit_iter ... ok
blam! test tests::rank_iter ... ok
blam! test tests::rank_to_str ... ok
blam! test tests::suit_char ... ok
blam! test tests::suit_sort ... ok
blam! test tests::suit_to_str ... ok
blam! 
blam! test result: ok. 25 passed; 0 failed; 0 ignored; 0 measured
blam! 
kablam!    Doc-tests deckofcards
blam! 
blam! running 4 tests
blam! test card_0 ... FAILED
blam! test combine_hands_0 ... FAILED
blam! test card::Card_0 ... FAILED
blam! test hand_0 ... FAILED
blam! 
blam! failures:
blam! 
blam! ---- card_0 stdout ----
blam! 	error: macro undefined: 'card!'
blam!  --> <anon>:2:12
blam!   |
blam! 2 | let card = card!("AS");
blam!   |            ^^^^
blam! 
blam! error: aborting due to previous error
blam! 
blam! thread 'card_0' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:461
blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
blam! thread 'card_0' panicked at 'couldn't compile the test', ../src/librustdoc/test.rs:275
blam! 
blam! ---- combine_hands_0 stdout ----
blam! 	error: macro undefined: 'combine_hands!'
blam!  --> <anon>:2:21
blam!   |
blam! 2 | let hand_combined = combine_hands!(hand1, hand2);
blam!   |                     ^^^^^^^^^^^^^
blam! 
blam! error: aborting due to previous error
blam! 
blam! thread 'combine_hands_0' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:461
blam! thread 'combine_hands_0' panicked at 'couldn't compile the test', ../src/librustdoc/test.rs:275
blam! 
blam! ---- card::Card_0 stdout ----
blam! 	error[E0433]: failed to resolve. Use of undeclared type or module `Card`
blam!  --> <anon>:2:12
blam!   |
blam! 2 | let card = Card::new(Rank::Jack, Suit::Hearts);
blam!   |            ^^^^^^^^^ Use of undeclared type or module `Card`
blam! 
blam! error[E0433]: failed to resolve. Use of undeclared type or module `Rank`
blam!  --> <anon>:2:22
blam!   |
blam! 2 | let card = Card::new(Rank::Jack, Suit::Hearts);
blam!   |                      ^^^^^^^^^^ Use of undeclared type or module `Rank`
blam! 
blam! error[E0433]: failed to resolve. Use of undeclared type or module `Suit`
blam!  --> <anon>:2:34
blam!   |
blam! 2 | let card = Card::new(Rank::Jack, Suit::Hearts);
blam!   |                                  ^^^^^^^^^^^^ Use of undeclared type or module `Suit`
blam! 
blam! error: aborting due to previous error(s)
blam! 
blam! thread 'card::Card_0' panicked at 'Box<Any>', ../src/librustc/session/mod.rs:191
blam! 
blam! ---- hand_0 stdout ----
blam! 	error: macro undefined: 'hand!'
blam!  --> <anon>:2:12
blam!   |
blam! 2 | let hand = hand!("QH", "2D");
blam!   |            ^^^^
blam! 
blam! error: aborting due to previous error
blam! 
blam! thread 'hand_0' panicked at 'Box<Any>', ../src/librustc_errors/lib.rs:461
blam! thread 'hand_0' panicked at 'couldn't compile the test', ../src/librustdoc/test.rs:275
blam! 
blam! 
blam! failures:
blam!     card::Card_0
blam!     card_0
blam!     combine_hands_0
blam!     hand_0
blam! 
blam! test result: FAILED. 0 passed; 4 failed; 0 ignored; 0 measured
blam! 
kablam! error: test failed
boom! running `docker rm -f bf28da86a316e75fd99550307f3adb51f4343fb151ccee47f840524990802552`
blam! bf28da86a316e75fd99550307f3adb51f4343fb151ccee47f840524990802552
