boom! testing rain-0.2.2 against stable for beta
boom! running: cargo +stable build --frozen
boom! creating container for: cargo +stable build --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/beta/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/beta/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable build --frozen cargobomb`
blam! 7fb0a25f96373943102c40016bb3f261e05719adea2e79ca21f929a40e313da9
boom! running `docker start -a 7fb0a25f96373943102c40016bb3f261e05719adea2e79ca21f929a40e313da9`
kablam!    Compiling rain v0.2.2 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.83 secs
boom! running `docker rm -f 7fb0a25f96373943102c40016bb3f261e05719adea2e79ca21f929a40e313da9`
blam! 7fb0a25f96373943102c40016bb3f261e05719adea2e79ca21f929a40e313da9
boom! running: cargo +stable test --frozen --no-run
boom! creating container for: cargo +stable test --frozen --no-run
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/beta/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/beta/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen --no-run cargobomb`
blam! cf28414a6dbf80b5f9848ce9ac550a30307ad0c282ee2c865d27db15384c17c7
boom! running `docker start -a cf28414a6dbf80b5f9848ce9ac550a30307ad0c282ee2c865d27db15384c17c7`
kablam!    Compiling rain v0.2.2 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 2.55 secs
boom! running `docker rm -f cf28414a6dbf80b5f9848ce9ac550a30307ad0c282ee2c865d27db15384c17c7`
blam! cf28414a6dbf80b5f9848ce9ac550a30307ad0c282ee2c865d27db15384c17c7
boom! running: cargo +stable test --frozen
boom! creating container for: cargo +stable test --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/beta/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/beta/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen cargobomb`
blam! f77543561e721b728246bfefc789a446a6b794913efbba6b53a66f6086e3db15
boom! running `docker start -a f77543561e721b728246bfefc789a446a6b794913efbba6b53a66f6086e3db15`
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
kablam!      Running /target/debug/deps/error-e733f0f1d9f16484
blam! 
blam! running 1 test
blam! test success_convert_from_io_error ... ok
blam! 
blam! test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured
blam! 
kablam!      Running /target/debug/deps/lib-1f29155b0eaae2f0
blam! 
blam! running 8 tests
blam! test add_remove_success_3 ... FAILED
blam! test add_remove_success_1 ... FAILED
blam! test add_remove_success_4 ... FAILED
blam! test add_remove_success_signed_integer ... FAILED
blam! test add_remove_success_2 ... FAILED
blam! test print_long_prefix_success ... FAILED
blam! test print_if_new_data_success ... FAILED
blam! test random_add_remove_success ... FAILED
blam! 
blam! failures:
blam! 
blam! ---- add_remove_success_3 stdout ----
blam! 	thread 'add_remove_success_3' panicked at 'assertion failed: graph.print().is_ok()', tests/lib.rs:57
kablam! error: test failed
blam! 
blam! ---- add_remove_success_1 stdout ----
blam! 	thread 'add_remove_success_1' panicked at 'assertion failed: graph.print().is_ok()', tests/lib.rs:16
blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
blam! 
blam! ---- add_remove_success_4 stdout ----
blam! 	thread 'add_remove_success_4' panicked at 'assertion failed: graph.print().is_ok()', tests/lib.rs:71
blam! 
blam! ---- add_remove_success_signed_integer stdout ----
blam! 	thread 'add_remove_success_signed_integer' panicked at 'assertion failed: graph.print().is_ok()', tests/lib.rs:145
blam! 
blam! ---- add_remove_success_2 stdout ----
blam! 	Logging failed: Could not create terminal.
blam! thread 'add_remove_success_2' panicked at 'assertion failed: graph.print().is_ok()', tests/lib.rs:47
blam! 
blam! ---- print_long_prefix_success stdout ----
blam! 	thread 'print_long_prefix_success' panicked at 'assertion failed: graph.print().is_ok()', tests/lib.rs:90
blam! 
blam! ---- print_if_new_data_success stdout ----
blam! 	thread 'print_if_new_data_success' panicked at 'called `Result::unwrap()` on an `Err` value: Code: Other, Description: Unable to get the terminal size.', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! 
blam! ---- random_add_remove_success stdout ----
blam! 	thread 'random_add_remove_success' panicked at 'assertion failed: graph.print_if_new_data().is_ok()', tests/lib.rs:133
blam! 
blam! 
blam! failures:
blam!     add_remove_success_1
blam!     add_remove_success_2
blam!     add_remove_success_3
blam!     add_remove_success_4
blam!     add_remove_success_signed_integer
blam!     print_if_new_data_success
blam!     print_long_prefix_success
blam!     random_add_remove_success
blam! 
blam! test result: FAILED. 0 passed; 8 failed; 0 ignored; 0 measured
blam! 
boom! running `docker rm -f f77543561e721b728246bfefc789a446a6b794913efbba6b53a66f6086e3db15`
blam! f77543561e721b728246bfefc789a446a6b794913efbba6b53a66f6086e3db15
