boom! testing text_io-0.1.6 against stable for beta
boom! running: cargo +stable build --frozen
boom! creating container for: cargo +stable build --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/beta/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/beta/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable build --frozen cargobomb`
blam! 9c6220a7de21b3607edc5a9523ca531f6eef3bf0eec8e009c20b109aeb6e4545
boom! running `docker start -a 9c6220a7de21b3607edc5a9523ca531f6eef3bf0eec8e009c20b109aeb6e4545`
kablam!    Compiling text_io v0.1.6 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.31 secs
boom! running `docker rm -f 9c6220a7de21b3607edc5a9523ca531f6eef3bf0eec8e009c20b109aeb6e4545`
blam! 9c6220a7de21b3607edc5a9523ca531f6eef3bf0eec8e009c20b109aeb6e4545
boom! running: cargo +stable test --frozen --no-run
boom! creating container for: cargo +stable test --frozen --no-run
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/beta/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/beta/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen --no-run cargobomb`
blam! 6317c53386e7fe7ae5f4aed1bb9de44925d44e12473d6b19b6ca493872466847
boom! running `docker start -a 6317c53386e7fe7ae5f4aed1bb9de44925d44e12473d6b19b6ca493872466847`
kablam!    Compiling text_io v0.1.6 (file:///source)
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!  --> tests/module.rs:6:9
kablam!   |
kablam! 6 |         scan!(text.bytes() => "{}:{}", a, b);
kablam!   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!   |
kablam!   = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!  --> tests/read_str.rs:5:20
kablam!   |
kablam! 5 |     let val: i32 = read!("{}", "42".bytes());
kablam!   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!   |
kablam!   = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:11:23
kablam!    |
kablam! 11 |     let val: String = read!("{}  64", "42  64".bytes());
kablam!    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:19:20
kablam!    |
kablam! 19 |     let val: i32 = read!("The answer is {}!!!11einself\n", file);
kablam!    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:21:21
kablam!    |
kablam! 21 |     let s: String = read!("There is {} spoon", file);
kablam!    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:31:5
kablam!    |
kablam! 31 |     scan!(file => "The answer is {}!!!11einself\nThere is {} spoon", val, *s);
kablam!    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:39:5
kablam!    |
kablam! 39 |     scan!("42".bytes() => "{}", val);
kablam!    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:43:5
kablam!    |
kablam! 43 |     scan!("<b>12</b>".bytes() => "<b>{}</b>", i);
kablam!    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:48:5
kablam!    |
kablam! 48 |     scan!(stdin => "{}", i);
kablam!    |     ^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:49:5
kablam!    |
kablam! 49 |     scan!(stdin => "{}", j);
kablam!    |     ^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 4.11 secs
boom! running `docker rm -f 6317c53386e7fe7ae5f4aed1bb9de44925d44e12473d6b19b6ca493872466847`
blam! 6317c53386e7fe7ae5f4aed1bb9de44925d44e12473d6b19b6ca493872466847
boom! running: cargo +stable test --frozen
boom! creating container for: cargo +stable test --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/beta/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/beta/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen cargobomb`
blam! f7937dc2ee83a6302fb16297bad9d87cc1297cf02f2f0f0be89ec529369f2a63
boom! running `docker start -a f7937dc2ee83a6302fb16297bad9d87cc1297cf02f2f0f0be89ec529369f2a63`
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
kablam!      Running /target/debug/deps/module-97170a843a504ee1
blam! 
blam! running 1 test
blam! test calling_scan_in_submodule ... ok
blam! 
kablam!      Running /target/debug/deps/read_str-98b44c82325c79c9
blam! test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured
blam! 
blam! 
blam! running 5 tests
blam! test simple ... ok
blam! test scan ... ok
blam! test file_scan ... ok
blam! test file ... ok
blam! test simple_spaces ... ok
blam! 
blam! test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured
blam! 
kablam!      Running /target/debug/deps/text_io-7497ef39b600d440
blam! 
blam! running 0 tests
blam! 
blam! test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
blam! 
kablam!      Running /target/debug/deps/tuple-16a990451f8b1be1
blam! 
blam! running 5 tests
blam! test run_read_simple ... FAILED
blam! test run_read ... FAILED
blam! test run_scan_simple ... FAILED
blam! test run_scan ... FAILED
blam! test run_unsupported_formatting_trait ... ok
blam! 
blam! failures:
blam! 
blam! ---- run_read_simple stdout ----
blam! 	thread 'run_read_simple' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
blam! 
blam! ---- run_read stdout ----
blam! 	thread 'run_read' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! 
blam! ---- run_scan_simple stdout ----
blam! 	thread 'run_scan_simple' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! 
blam! ---- run_scan stdout ----
blam! 	thread 'run_scan' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! 
blam! 
blam! failures:
blam!     run_read
blam!     run_read_simple
blam!     run_scan
blam!     run_scan_simple
blam! 
blam! test result: FAILED. 1 passed; 4 failed; 0 ignored; 0 measured
blam! 
kablam! error: test failed
boom! running `docker rm -f f7937dc2ee83a6302fb16297bad9d87cc1297cf02f2f0f0be89ec529369f2a63`
blam! f7937dc2ee83a6302fb16297bad9d87cc1297cf02f2f0f0be89ec529369f2a63
