boom! testing text_io-0.1.5 against stable for nightly
boom! running: cargo +stable build --frozen
boom! creating container for: cargo +stable build --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable build --frozen cargobomb`
blam! 351ac58c308f0e1362935f3598060f4eeeb41ace1a34b1606670e6de612cb003
boom! running `docker start -a 351ac58c308f0e1362935f3598060f4eeeb41ace1a34b1606670e6de612cb003`
kablam!    Compiling text_io v0.1.5 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.23 secs
boom! running `docker rm -f 351ac58c308f0e1362935f3598060f4eeeb41ace1a34b1606670e6de612cb003`
blam! 351ac58c308f0e1362935f3598060f4eeeb41ace1a34b1606670e6de612cb003
boom! running: cargo +stable test --frozen --no-run
boom! creating container for: cargo +stable test --frozen --no-run
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen --no-run cargobomb`
blam! c171d3e33c6d132dfd1bce885e02682c464f328158589c56b625e7b5d9d3312b
boom! running `docker start -a c171d3e33c6d132dfd1bce885e02682c464f328158589c56b625e7b5d9d3312b`
kablam!    Compiling text_io v0.1.5 (file:///source)
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!  --> tests/read_str.rs:5:20
kablam!   |
kablam! 5 |     let val: i32 = read!("{}", "42".bytes());
kablam!   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!   |
kablam!   = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:11:23
kablam!    |
kablam! 11 |     let val: String = read!("{}  64", "42  64".bytes());
kablam!    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:19:20
kablam!    |
kablam! 19 |     let val: i32 = read!("The answer is {}!!!11einself\n", file);
kablam!    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:21:21
kablam!    |
kablam! 21 |     let s: String = read!("There is {} spoon", file);
kablam!    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:31:5
kablam!    |
kablam! 31 |     scan!(file => "The answer is {}!!!11einself\nThere is {} spoon", val, *s);
kablam!    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:39:5
kablam!    |
kablam! 39 |     scan!("42".bytes() => "{}", val);
kablam!    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!   --> tests/read_str.rs:43:5
kablam!    |
kablam! 43 |     scan!("<b>12</b>".bytes() => "<b>{}</b>", i);
kablam!    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!    |
kablam!    = note: this error originates in a macro outside of the current crate
kablam! 
kablam! warning: unused import: `:: std :: io :: Read`, #[warn(unused_imports)] on by default
kablam!  --> tests/module.rs:6:9
kablam!   |
kablam! 6 |         scan!(text.bytes() => "{}:{}", a, b);
kablam!   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
kablam!   |
kablam!   = note: this error originates in a macro outside of the current crate
kablam! 
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 4.61 secs
boom! running `docker rm -f c171d3e33c6d132dfd1bce885e02682c464f328158589c56b625e7b5d9d3312b`
blam! c171d3e33c6d132dfd1bce885e02682c464f328158589c56b625e7b5d9d3312b
boom! running: cargo +stable test --frozen
boom! creating container for: cargo +stable test --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen cargobomb`
blam! 86251244724bfd1483be582703e72e280124092aa058fb74ced5a8399dbc6510
boom! running `docker start -a 86251244724bfd1483be582703e72e280124092aa058fb74ced5a8399dbc6510`
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
kablam!      Running /target/debug/module-637b6f7d68905b4b
blam! 
blam! running 1 test
blam! test calling_scan_in_submodule ... ok
blam! 
blam! test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured
blam! 
kablam!      Running /target/debug/read_str-4edc2146c26cdc05
blam! 
blam! running 5 tests
blam! test simple ... ok
blam! test file ... ok
blam! test file_scan ... ok
blam! test simple_spaces ... ok
blam! test scan ... ok
blam! 
blam! test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured
blam! 
kablam!      Running /target/debug/deps/text_io-303725b168e7934b
blam! 
blam! running 0 tests
blam! 
blam! test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
blam! 
kablam!      Running /target/debug/tuple-d963baf30fededf5
blam! 
blam! running 4 tests
blam! test run_read ... FAILED
blam! test run_read_simple ... FAILED
blam! test run_scan ... FAILED
blam! test run_scan_simple ... FAILED
blam! 
blam! failures:
blam! 
blam! ---- run_read stdout ----
blam! 	thread 'run_read' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
blam! 
blam! ---- run_read_simple stdout ----
blam! 	thread 'run_read_simple' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- run_scan stdout ----
blam! 	thread 'run_scan' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
blam! 
blam! ---- run_scan_simple stdout ----
blam! 	thread 'run_scan_simple' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:837
blam! 
blam! 
blam! failures:
blam!     run_read
blam!     run_read_simple
blam!     run_scan
blam!     run_scan_simple
blam! 
blam! test result: FAILED. 0 passed; 4 failed; 0 ignored; 0 measured
blam! 
kablam! error: test failed
boom! running `docker rm -f 86251244724bfd1483be582703e72e280124092aa058fb74ced5a8399dbc6510`
blam! 86251244724bfd1483be582703e72e280124092aa058fb74ced5a8399dbc6510
