boom! testing rain-0.2.2 against stable for nightly
boom! running: cargo +stable build --frozen
boom! creating container for: cargo +stable build --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable build --frozen cargobomb`
blam! 5b0be29c217b332b87bb212ed95c3748414c675dcfe717510f16f5190a986e50
boom! running `docker start -a 5b0be29c217b332b87bb212ed95c3748414c675dcfe717510f16f5190a986e50`
kablam!    Compiling rain v0.2.2 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.69 secs
boom! running `docker rm -f 5b0be29c217b332b87bb212ed95c3748414c675dcfe717510f16f5190a986e50`
blam! 5b0be29c217b332b87bb212ed95c3748414c675dcfe717510f16f5190a986e50
boom! running: cargo +stable test --frozen --no-run
boom! creating container for: cargo +stable test --frozen --no-run
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen --no-run cargobomb`
blam! e434e419eac5ce10389b82a5bea2fb510fc3baf5c448526100125945954a623d
boom! running `docker start -a e434e419eac5ce10389b82a5bea2fb510fc3baf5c448526100125945954a623d`
kablam!    Compiling rain v0.2.2 (file:///source)
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 2.44 secs
boom! running `docker rm -f e434e419eac5ce10389b82a5bea2fb510fc3baf5c448526100125945954a623d`
blam! e434e419eac5ce10389b82a5bea2fb510fc3baf5c448526100125945954a623d
boom! running: cargo +stable test --frozen
boom! creating container for: cargo +stable test --frozen
boom! running `docker create -v /home/ec2-user/cargobomb/./work/local/test-source/nightly/stable:/source:ro -v /home/ec2-user/cargobomb/./work/local/cargo-home:/cargo-home:ro -v /home/ec2-user/cargobomb/./work/local/rustup-home:/rustup-home:ro -v /home/ec2-user/cargobomb/./work/local/target-dirs/nightly/stable:/target:rw -e USER_ID=500 -e CMD=cargo +stable test --frozen cargobomb`
blam! 371ff042480d4633317904ac7770076d0e074201244d4a09c8eee494e729b376
boom! running `docker start -a 371ff042480d4633317904ac7770076d0e074201244d4a09c8eee494e729b376`
kablam!     Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
kablam!      Running /target/debug/deps/error-e733f0f1d9f16484
blam! 
blam! running 1 test
blam! test success_convert_from_io_error ... ok
blam! 
blam! test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured
blam! 
kablam!      Running /target/debug/deps/lib-1f29155b0eaae2f0
blam! 
blam! running 8 tests
blam! test add_remove_success_4 ... FAILED
blam! test add_remove_success_3 ... FAILED
blam! test add_remove_success_1 ... FAILED
blam! test print_long_prefix_success ... FAILED
blam! test add_remove_success_2 ... FAILED
blam! test add_remove_success_signed_integer ... FAILED
blam! test print_if_new_data_success ... FAILED
blam! test random_add_remove_success ... FAILED
kablam! error: test failed
blam! 
blam! failures:
blam! 
blam! ---- add_remove_success_4 stdout ----
blam! 	thread 'add_remove_success_4' panicked at 'assertion failed: graph.print().is_ok()', tests/lib.rs:71
blam! note: Run with `RUST_BACKTRACE=1` for a backtrace.
blam! 
blam! ---- add_remove_success_3 stdout ----
blam! 	thread 'add_remove_success_3' panicked at 'assertion failed: graph.print().is_ok()', tests/lib.rs:57
blam! 
blam! ---- add_remove_success_1 stdout ----
blam! 	Logging failed: Could not create terminal.
blam! thread 'add_remove_success_1' panicked at 'assertion failed: graph.print().is_ok()', tests/lib.rs:16
blam! 
blam! ---- print_long_prefix_success stdout ----
blam! 	thread 'print_long_prefix_success' panicked at 'assertion failed: graph.print().is_ok()', tests/lib.rs:90
blam! 
blam! ---- add_remove_success_2 stdout ----
blam! 	thread 'add_remove_success_2' panicked at 'assertion failed: graph.print().is_ok()', tests/lib.rs:47
blam! 
blam! ---- add_remove_success_signed_integer stdout ----
blam! 	thread 'add_remove_success_signed_integer' panicked at 'assertion failed: graph.print().is_ok()', tests/lib.rs:145
blam! 
blam! ---- print_if_new_data_success stdout ----
blam! 	thread 'print_if_new_data_success' panicked at 'called `Result::unwrap()` on an `Err` value: Code: Other, Description: Unable to get the terminal size.', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:837
blam! 
blam! ---- random_add_remove_success stdout ----
blam! 	thread 'random_add_remove_success' panicked at 'assertion failed: graph.print_if_new_data().is_ok()', tests/lib.rs:133
blam! 
blam! 
blam! failures:
blam!     add_remove_success_1
blam!     add_remove_success_2
blam!     add_remove_success_3
blam!     add_remove_success_4
blam!     add_remove_success_signed_integer
blam!     print_if_new_data_success
blam!     print_long_prefix_success
blam!     random_add_remove_success
blam! 
blam! test result: FAILED. 0 passed; 8 failed; 0 ignored; 0 measured
blam! 
boom! running `docker rm -f 371ff042480d4633317904ac7770076d0e074201244d4a09c8eee494e729b376`
blam! 371ff042480d4633317904ac7770076d0e074201244d4a09c8eee494e729b376
